name = "CreateOrigin"
author = "Chikage"
version = "v4.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "553839a646a3d37f14cb9faea24f72769ca7e4907641a70e90d27265711ec23a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
