name = "CreateOrigin"
author = "Chikage"
version = "v5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9ae384ea99959c1c95b9ec4cb0fa3f23245374443a938b2a60cf90f84150667"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
