name = "CreateOrigin"
author = "Chikage"
version = "v4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be82a9b96606e9665430cb4665ac06612e7fa6a8ec400834b3cf02d7d2660f06"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
