name = "CreateOrigin"
author = "Chikage"
version = "v4.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ed58e79dfb839164869a9ca4e1a85d60b1418f994690ba52d0ad9356eab4a1f"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
