name = "CreateOrigin"
author = "Chikage"
version = "v3.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ae93c3e83c70d13ef40a78d841bab095ccdab017b02ef779bb99829f2b261b2"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
