name = "CreateOrigin"
author = "Chikage"
version = "v4.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f6c65bcbb810cbb4f900196b6a0257634e0df73e92056f9bbcc0ed2e00348af"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
