name = "CreateOrigin"
author = "Chikage"
version = "v4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01d3738ef6937d63b0c309b446dff30e3c56db218c4d5ec9b34e59c00bcacaba"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
