name = "CreateOrigin"
author = "Chikage"
version = "v4.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6610e5875f821d0206e3e2cefb820569007ab02f2415c345f722967806d54df8"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
