name = "CreateOrigin"
author = "Chikage"
version = "v4.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f4b898e3137e8e225411bd7f31ef3c77ec094135088f534fa9733fb62fb74bd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
