name = "CreateOrigin"
author = "Chikage"
version = "v4.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b58fd8a74afcfd6e6d0a27aa7503463e65b4ebbdb13bb867225559160f90e20"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
