name = "CreateOrigin"
author = "Chikage"
version = "v3.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec0ebbf5b177a7b147ba74ee2c8102f2a122a44f587e2589a1a2eab80161f6e2"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
