name = "CreateOrigin"
author = "Chikage"
version = "v3.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4077f96ab56192735a1d4b1a94077b4b07cb6fd444263fabb59b713d98afcf7"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
