name = "CreateOrigin"
author = "Chikage"
version = "3.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdff73c7300a4268e5d0407cddac477e1a7ccf9ecfd006a83180c89548451c5e"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
