name = "CreateOrigin"
author = "Chikage"
version = "v3.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b5114e1e6cb74a74e2a6a06b315c6298880ec88671818afe3daf08ca1dbdf93"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
