name = "CreateOrigin"
author = "Chikage"
version = "v3.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "307bd45a7ec3f7e4c48730f65e8e6140ada8c90d6b344a4264ae85678090af8d"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
