name = "CreateOrigin"
author = "Chikage"
version = "v3.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "092f48dc8fc30c82d8eef60aa08736341be0bdcc98bfdd75a4ed390aa88b485d"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
