name = "CreateOrigin"
author = "Chikage"
version = "v4.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1da7b0a3f801ff780a3b25ac1cb83b62c98ac639c144d6056b24cca86114a4d6"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
