name = "CreateOrigin"
author = "Chikage"
version = "v4.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b507d529c9b2be67d2ebb84911b6fbd3a08020494603f162b0086c6ec8350884"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
