name = "CreateOrigin"
author = "Chikage"
version = "v3.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a8fa5c861205be1092d67336d4d0782253c56f193243afe7ed4f377946b669"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
