name = "CreateOrigin"
author = "Chikage"
version = "v3.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "677c2694a3187c0ff6bb8531db70aab7f6c1a60fedb9e2967e8dd56965f89fe6"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
