name = "CreateOrigin"
author = "Chikage"
version = "v4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "334999676af70ce82c6daf985799a4292fed32cb4dcb9c72a40658fa64f20580"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
