name = "CreateOrigin"
author = "Chikage"
version = "v4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "636de5277beecd797e7f5cda14264af2ce49a032e1311fbf8808c5aea0ba30a0"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
