name = "CreateOrigin"
author = "Chikage"
version = "v4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29ee60389dd1b7b8cc3fbf3326d1698fd5d45ca7310bb5d0c0d7e8d17d49d2ee"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
