name = "CreateOrigin"
author = "Chikage"
version = "v3.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f83b9719de92fc90351086702c6d777fec19d67ccafde5e4473c7c5b4bc04a"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
