name = "CreateOrigin"
author = "Chikage"
version = "v4.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0c4df040cfd3a84bff916de562484b628256deaf52ae72d0342acc1f7da68ef"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
