name = "CreateOrigin"
author = "Chikage"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c89f9ef16f9313fb0cb68d35093a0639f766d72bbd691a749e91be76058eeda"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
