name = "CreateOrigin"
author = "Chikage"
version = "v4.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0a131c3647deff7e0dfe32e2a1027b2199decbef8445ab2830156f481ccbb8"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
