name = "CreateOrigin"
author = "Chikage"
version = "v4.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "140e0505521c7fdb2581de1968e439b9460da0a38c83b4f45a6152411ba6212a"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
