name = "CreateOrigin"
author = "Chikage"
version = "v4.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7e623734f2cb3f956759cadc676e95c7b92ed14dfb6b8db5a0bf6599606d99e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
