name = "CreateOrigin"
author = "Chikage"
version = "v4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cefb3516859bbc0e2a29955ba6aaf220861c957744359cff588f86a092a7089e"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
