name = "CreateOrigin"
author = "Chikage"
version = "v4.6.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b6ec3e14d9cca11eea81ebfbe1c522b7c974bec09fd7dc04ffc420b7500b9d3"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
