name = "CreateOrigin"
author = "Chikage"
version = "v4.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c081d270b682c964e4f601665ed025e088d35ff6a3481832eb21752b8ec1f306"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
