name = "CreateOrigin"
author = "Chikage"
version = "v4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e3d1946d98af0d4229ad9d06ceb72e94d891345102b4e197b6c7cc40bf853e7"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
