name = "CreateOrigin"
author = "Chikage"
version = "v3.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0c2a5ab7d16e7f1476deeecc7ed5305ad7824d5a4444eee2c4fca6696aadcf3"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
