name = "CreateOrigin"
author = "Chikage"
version = "3.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "280c12bd4767206de636ba0d00c537030f73477cb6446d86071bd83748225fd3"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
