name = "CreateOrigin"
author = "Chikage"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9abe9d64475458f0bcab0a00bccc0f981ee7a659a8fe353f2a6f3fc9c435d20f"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
