name = "CreateOrigin"
author = "Chikage"
version = "v4.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49944a0f23e81f2a1941ee30e4fa495d67d5d8eafdfc94368ca56fd2f293aadd"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
