name = "CreateOrigin"
author = "Chikage"
version = "v4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f93588eab7f12f37ad80152bb0637c03c64eabde19cfa14a209ee39ca5bc9431"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
