:: Start script generated by ServerPackCreator.
:: This script checks for the Minecraft and Fabric JAR-files, and if they are not found, they are downloaded and installed.
:: If everything is in order, the server is started.
@ECHO off

SET JAVA="java"
SET MINECRAFT="1.18.2"
SET FABRIC="0.14.10"
SET INSTALLER="0.11.1"
SET ARGS="-Xmx5G"
SET OTHERARGS="-Dlog4j2.formatMsgNoLookups=true"

SET AGREE="I agree"

IF NOT EXIST fabric-server-launch.jar (

  ECHO Fabric Server JAR-file not found. Downloading installer...
  powershell -Command "(New-Object Net.WebClient).DownloadFile('https://maven.fabricmc.net/net/fabricmc/fabric-installer/%INSTALLER%/fabric-installer-%INSTALLER%.jar', 'fabric-installer.jar')"

  IF EXIST fabric-installer.jar (

    ECHO Installer downloaded. Installing...
    java -jar fabric-installer.jar server -mcversion %MINECRAFT% -loader %FABRIC% -downloadMinecraft

    IF EXIST fabric-server-launch.jar (
      RMDIR /S /Q .fabric-installer
      DEL fabric-installer.jar
      ECHO Installation complete. fabric-installer.jar and installation files deleted.
    )

  ) ELSE (
    ECHO fabric-installer.jar not found. Maybe the Fabric servers are having trouble.
    ECHO Please try again in a couple of minutes.
  )
) ELSE (
  ECHO fabric-server-launch.jar present. Moving on...
)

IF NOT EXIST server.jar (
  ECHO Minecraft Server JAR-file not found. Downloading...
  powershell -Command "(New-Object Net.WebClient).DownloadFile('Optional[https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar]', 'server.jar')"
) ELSE (
  ECHO server.jar present. Moving on...
)

IF NOT EXIST eula.txt (
  ECHO Mojang's EULA has not yet been accepted. In order to run a Minecraft server, you must accept Mojang's EULA.
  ECHO Mojang's EULA is available to read at https://account.mojang.com/documents/minecraft_eula
  ECHO If you agree to Mojang's EULA then type "I agree"
  set /P "Response="
  IF "%Response%" == "%AGREE%" (
    ECHO User agreed to Mojang's EULA.
    ECHO #By changing the setting below to TRUE you are indicating your agreement to our EULA ^(https://account.mojang.com/documents/minecraft_eula^).> eula.txt
    ECHO eula=true>> eula.txt
  ) else (
    ECHO User did not agree to Mojang's EULA. 
  )
) ELSE (
  ECHO eula.txt present. Moving on...
)

ECHO Starting server...
ECHO Minecraft version: %MINECRAFT%
ECHO Fabric version: %FABRIC%
ECHO Java version:
%JAVA% --version
ECHO Java args: %ARGS%

%JAVA% "%OTHERARGS%" %ARGS% -jar fabric-server-launch.jar nogui

PAUSE