#Couple regardless of whether the player is sneaking
ignore_sneaking = false
#Couple fence gates above and below on the same axis
couple_fence_gates = false
#Couple doors with opposing hinges
couple_doors = true
#Couple trapdoors along either sides and opposing
couple_trapdoors = false

