name: AutoBuildPackWhenPushh

on:
  push: 

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' 
          
      - name: build modpack
        run: bash build.sh
        

      - name: update artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mrpack
          path: ./*.mrpack
