# This is a basic workflow to help you get started with Actions

name: AutoBuildPack

# Controls when the workflow will run
on:
  push: 
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Release')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' 

      - name: get version
        id: pack_version
        run: |
          echo "pack_version=$(git show -s --format=%B | head -1 | grep -o '[0-9\.]*$')" >> $GITHUB_ENV
          
      # Runs a single command using the runners shell
      - name: build modpack
        run: bash build.sh

      - name: release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.pack_version }}
          allowUpdates: true
          tag: ${{ env.pack_version }}
          commit: main
          replacesArtifacts: true
          token: ${{ secrets.SECRET }}
          artifacts: ./*.mrpack

  preRelease:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'PreRelease')"

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' 

      - name: get version
        run: |
          echo "pack_version=$(git show -s --format=%B | head -1 | grep -o '[0-9\.]*$')" >> $GITHUB_ENV

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          bash updateVersion.sh

      - name: commit
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"
          git add .
          git commit -m "Release $pack_version"
          git push -f
