name: AutoBuildPack

on:
  push: 
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  PROJECT_ID: Cc9a9YwB
  RELEASE_TYPE: release
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' 

      - name: get info
        run: |
          echo "pack_version=$(git show -s --format=%B | head -1 | grep -o 'v[0-9\.]*$')" >> $GITHUB_ENV
          echo "game_version=$(grep -oP '(?<=minecraft = \")[0-9.]+' ./pack.toml)" >> $GITHUB_ENV
          echo "loader=$(grep -oP '(quilt|fabric|forge)' ./pack.toml)" >> $GITHUB_ENV
          echo "pack_name=$(grep -oP '(?<=name = \")[\w\s-_]+' ./pack.toml)" >> $GITHUB_ENV
          
      - name: build modpack
        run: bash build.sh
        
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.SECRET }}
          exclude_types: other

      - name: release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.pack_version }}
          body: ${{ steps.changelog.outputs.changes }}
          allowUpdates: true
          tag: ${{ env.pack_version }}
          commit: main
          replacesArtifacts: true
          token: ${{ secrets.SECRET }}
          artifacts: ./${{ env.pack_name }}-${{ env.pack_version }}.mrpack
      
      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1.0.0
        with:
          token: ${{ secrets.MODRINTH }}
          file_path: ./${{ env.pack_name }}-${{ env.pack_version }}.mrpack
          name: ${{ env.pack_version }}
          version: ${{ env.pack_version }}
          changelog: ${{ steps.changelog.outputs.changes }}
          game_versions: ${{ env.game_version }}
          release_type: ${{ env.RELEASE_TYPE }}
          loaders: ${{ env.loader }}
          featured: true
          project_id: ${{ env.PROJECT_ID }}
