name: PreRelease

on:
  push: 
    branches: [ main ]

jobs:
  preRelease:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'PreRelease')"

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.SECRET }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' 

      - name: get version
        run: |
          echo "pack_version=$(git show -s --format=%B | head -1 | grep -o '[0-9\.]*$')" >> $GITHUB_ENV

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          bash updateVersion.sh

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Release ${{ env.pack_version }}"
          tagging_message: ${{ env.pack_version }}

